#
name: donald-trump-frontend-charley
namespace: charley

replicaCount: 1

image:
  repository: lamenace90/donald-trump-app
  pullPolicy: Always
  tag: 'cb9d991'

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
