namespace: charley

# External access to the service in a cluster
ingress:
  enabled: true
  name: "donald-trump-charley"
  serviceNameFront: "donald-trump-frontend-charley"
  tls: true
  className: "nginx"
  host: "donald.cluster-2022-5.dopolytech.fr"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
